service:
  name: codebuild-slack-notifier

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize

provider:
  name: aws
  memorySize: 128
  runtime: nodejs8.10
  region: eu-west-1
  environment:
    SLACK_TOKEN: ${ssm:/codebuild-slack-notifier/slack_token~true}

functions:
  main:
    handler: index.handler
    reservedConcurrency: 1
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.codebuild"
            detail-type:
              - "CodeBuild Build State Change"
              - "CodeBuild Build Phase Change"
      - cloudwatchEvent:
          event:
            source:
              - "aws.codepipeline"
            detail-type:
              - "CodePipeline Pipeline Execution State Change"
              - "CodePipeline Stage Execution State Change"
              - "CodePipeline Action Execution State Change"

